In [1]:
import numpy as np


## DataTypes & Attributes

In [2]:
# Numpy main datatypes is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([
    [1,2.2,3],
    [4,5,56]
])

a3 = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
    ],
    [
        [10,11,12],
        [13,14,15],
        [16,17,18]
    ]
])


In [5]:
a2


array([[ 1. ,  2.2,  3. ],
       [ 4. ,  5. , 56. ]])

In [6]:
a3


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.ndim, a2.ndim, a3.ndim


(1, 2, 3)

In [9]:
a1.dtype, a2.dtype, a3.dtype



(dtype('int64'), dtype('float64'), dtype('int64'))

In [10]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [11]:
# create DataFrame from a NumPy array
import pandas as pd
df = pd.DataFrame(a2)
df


0    1     2
0  1.0  2.2   3.0
1  4.0  5.0  56.0

## Creating arrays

In [12]:
sample_array = a1

In [13]:
ones = np.ones((2,3))
ones


array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
range_array = np.arange(0,10,2)
range_array


array([0, 2, 4, 6, 8])

In [17]:
random_array = np.random.randint(0,10,size=(3,2,5))
random_array

array([[[0, 9, 1, 7, 1],
        [2, 9, 9, 2, 6]],

       [[7, 5, 2, 7, 5],
        [2, 7, 6, 6, 8]],

       [[5, 4, 4, 8, 5],
        [8, 0, 5, 4, 3]]])

In [18]:
random_array.size, random_array.shape


(30, (3, 2, 5))

In [21]:
random_array_2 = np.random.rand(6,2)
random_array_2

array([[0.11506811, 0.70403856],
       [0.19796618, 0.01472619],
       [0.57963808, 0.20250895],
       [0.75057517, 0.99432653],
       [0.27688435, 0.68363862],
       [0.26636517, 0.16824822]])