In [2]:
import numpy as np


## DataTypes & Attributes

In [3]:
# Numpy main datatypes is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([
    [1,2.2,3],
    [4,5,56]
])

a3 = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
    ],
    [
        [10,11,12],
        [13,14,15],
        [16,17,18]
    ]
])


In [6]:
a2


array([[ 1. ,  2.2,  3. ],
       [ 4. ,  5. , 56. ]])

In [7]:
a3


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.ndim, a2.ndim, a3.ndim


(1, 2, 3)

In [9]:
a1.dtype, a2.dtype, a3.dtype



(dtype('int64'), dtype('float64'), dtype('int64'))

In [10]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [11]:
# create DataFrame from a NumPy array
import pandas as pd
df = pd.DataFrame(a2)
df


0    1     2
0  1.0  2.2   3.0
1  4.0  5.0  56.0

## Creating arrays

In [12]:
sample_array = a1

In [13]:
ones = np.ones((2,3))

zeros = np.zeros((2,3))
ones , zeros

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[0., 0., 0.],
        [0., 0., 0.]]))

In [14]:
range_array = np.arange(0,10,2)
range_array


array([0, 2, 4, 6, 8])

In [15]:
random_array = np.random.randint(0,10,size=(3,2,5))
random_array

array([[[6, 5, 8, 6, 3],
        [0, 2, 0, 6, 2]],

       [[7, 9, 3, 1, 8],
        [6, 2, 1, 2, 2]],

       [[2, 6, 5, 7, 1],
        [8, 8, 5, 9, 6]]])

In [16]:
random_array.size, random_array.shape


(30, (3, 2, 5))

In [17]:
random_array_2 = np.random.rand(6,2)
random_array_2

array([[0.5691202 , 0.59724555],
       [0.11054693, 0.21408589],
       [0.1223233 , 0.58785929],
       [0.05518863, 0.37311332],
       [0.46843763, 0.76669432],
       [0.53672837, 0.70416022]])

In [18]:
# Pseudo-random numbers
np.random.seed(2)
random_array_4 = np.random.randint(10,size=(5,3))
random_array_4

array([[8, 8, 6],
       [2, 8, 7],
       [2, 1, 5],
       [4, 4, 5],
       [7, 3, 6]])

## Viewing arrays and matrices

In [19]:
# unique number
np.unique(random_array_4)


array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
a1, a2, a3


(array([1, 2, 3]),
 array([[ 1. ,  2.2,  3. ],
        [ 4. ,  5. , 56. ]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [21]:
a1[0], a2[0], a3[0]

(1,
 array([1. , 2.2, 3. ]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [22]:
a4 = np.random.randint(5,size=(2,3,4,5))
a4


array([[[[4, 2, 3, 3, 2],
         [1, 2, 4, 3, 0],
         [4, 3, 1, 2, 0],
         [4, 4, 2, 4, 2]],

        [[1, 0, 2, 2, 1],
         [0, 1, 0, 2, 1],
         [1, 1, 4, 2, 3],
         [0, 3, 0, 2, 2]],

        [[0, 4, 2, 0, 2],
         [4, 1, 3, 0, 2],
         [1, 4, 0, 1, 1],
         [1, 2, 4, 2, 3]]],


       [[[4, 2, 0, 2, 3],
         [3, 0, 0, 3, 3],
         [0, 0, 2, 3, 1],
         [2, 3, 4, 3, 3]],

        [[1, 4, 2, 3, 0],
         [0, 2, 4, 4, 3],
         [2, 1, 1, 1, 2],
         [1, 3, 0, 1, 0]],

        [[4, 3, 1, 3, 0],
         [0, 3, 2, 2, 2],
         [1, 3, 4, 3, 1],
         [0, 3, 0, 3, 1]]]])

In [23]:
# get the first 4 numbers of the inner most array
a4[:,:,:,:4]

array([[[[4, 2, 3, 3],
         [1, 2, 4, 3],
         [4, 3, 1, 2],
         [4, 4, 2, 4]],

        [[1, 0, 2, 2],
         [0, 1, 0, 2],
         [1, 1, 4, 2],
         [0, 3, 0, 2]],

        [[0, 4, 2, 0],
         [4, 1, 3, 0],
         [1, 4, 0, 1],
         [1, 2, 4, 2]]],


       [[[4, 2, 0, 2],
         [3, 0, 0, 3],
         [0, 0, 2, 3],
         [2, 3, 4, 3]],

        [[1, 4, 2, 3],
         [0, 2, 4, 4],
         [2, 1, 1, 1],
         [1, 3, 0, 1]],

        [[4, 3, 1, 3],
         [0, 3, 2, 2],
         [1, 3, 4, 3],
         [0, 3, 0, 3]]]])

## Manipulating & comparing arrays*

### Math

In [24]:
a1 + ones


array([[2., 3., 4.],
       [2., 3., 4.]])

In [26]:
a1 , a2

(array([1, 2, 3]),
 array([[ 1. ,  2.2,  3. ],
        [ 4. ,  5. , 56. ]]))

In [27]:
a1 * a2

array([[  1. ,   4.4,   9. ],
       [  4. ,  10. , 168. ]])

In [28]:
a3*a2

ValueError: operands could not be broadcast together with shapes (2,3,3) (2,3) 

In [29]:
# how to reshape numpy array
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [31]:
a2


array([[ 1. ,  2.2,  3. ],
       [ 4. ,  5. , 56. ]])

### aggregation

In [34]:
a1.sum()


6

In [35]:
massive_array = np.random.random(100000)


In [36]:
massive_array[:10]


array([0.80721114, 0.79822058, 0.55453947, 0.89514574, 0.9291399 ,
       0.97763339, 0.91771872, 0.04001124, 0.73282249, 0.89637388])

In [37]:
%timeit sum(massive_array)
%timeit massive_array.sum()


15.2 ms ± 735 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
37.4 µs ± 997 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [38]:
a2.min(), a2.max(), a2.mean()


(1.0, 56.0, 11.866666666666667)

In [39]:
# standard deviation is a measure of how spread out a group of number is from the mean
a2.std()

19.777652933438677

In [41]:
# variance is the measure of average degree to which each number is difference from the mean
a2.var()

391.15555555555557

### Reshaping & transposing

In [43]:
a2.shape , a2

((2, 3),
 array([[ 1. ,  2.2,  3. ],
        [ 4. ,  5. , 56. ]]))

In [44]:
a3.shape , a3



((2, 3, 3),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [47]:
a2.reshape(2,3,1) * a3

array([[[1.000e+00, 2.000e+00, 3.000e+00],
        [8.800e+00, 1.100e+01, 1.320e+01],
        [2.100e+01, 2.400e+01, 2.700e+01]],

       [[4.000e+01, 4.400e+01, 4.800e+01],
        [6.500e+01, 7.000e+01, 7.500e+01],
        [8.960e+02, 9.520e+02, 1.008e+03]]])

In [48]:
a2.shape , a2

((2, 3),
 array([[ 1. ,  2.2,  3. ],
        [ 4. ,  5. , 56. ]]))

In [49]:
a2.T.shape, a2.T

((3, 2),
 array([[ 1. ,  4. ],
        [ 2.2,  5. ],
        [ 3. , 56. ]]))

In [52]:
# dot product =produit scalaire
rand1 = np.random.randint(10,size=(5,3))
rand1

array([[5, 4, 1],
       [4, 0, 4],
       [7, 2, 5],
       [1, 6, 0],
       [8, 5, 2]])

In [53]:
rand2 = np.random.randint(low=2,high=8,size=(5,3))
rand2

array([[6, 7, 4],
       [5, 2, 2],
       [7, 4, 2],
       [4, 5, 7],
       [6, 5, 2]])

In [ ]:
rand1.shape, rand2.shape

In [54]:
np.dot(rand1,rand2)


ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

((5, 3), (5, 3))

In [56]:
rand1.shape , rand2.T.shape


((5, 3), (3, 5))

In [57]:
np.dot(rand1,rand2.T)

array([[62, 35, 53, 47, 52],
       [40, 28, 36, 44, 32],
       [76, 49, 67, 73, 62],
       [48, 17, 31, 34, 36],
       [91, 54, 80, 71, 77]])

In [58]:
np.dot(rand1,rand2.T).shape


(5, 5)

# Exercice

In [68]:
daily_consume = pd.DataFrame(
    np.random.randint(15,size=(5,3)),
    index=['dim',"lun","mar","mer","jeu"],
    columns=["pizza","banana","the"]
)
daily_consume

pizza  banana  the
dim     14      14    3
lun      7       3    2
mar     11      14   12
mer     11       3   11
jeu      4       4    9

In [69]:
price = pd.DataFrame(
    np.random.randint(20,size=(1,3)),
    index=['price'],
    columns=["pizza","banana","the"]
)
price

pizza  banana  the
price     10       5    0

In [70]:
total = np.dot(daily_consume,price.T)
total

array([[210],
       [ 85],
       [180],
       [125],
       [ 60]])

In [71]:
daily_consume["total ($)"] = (np.dot(price,daily_consume.T)).T

In [72]:
daily_consume


pizza  banana  the  total ($)
dim     14      14    3        210
lun      7       3    2         85
mar     11      14   12        180
mer     11       3   11        125
jeu      4       4    9         60

## Comparison Operation
https://numpy.org/doc/stable/reference/routines.logic.html

In [73]:
np.less(a1,a2)


array([[False,  True, False],
       [ True,  True,  True]])

In [74]:
a1 < a2


array([[False,  True, False],
       [ True,  True,  True]])

In [75]:
a1 , a2


(array([1, 2, 3]),
 array([[ 1. ,  2.2,  3. ],
        [ 4. ,  5. , 56. ]]))

## Sorting arrays


In [85]:
random_array = np.random.randint(10,size=(3,5))

In [86]:
random_array


array([[4, 7, 3, 3, 3],
       [1, 9, 9, 5, 4],
       [8, 7, 9, 0, 1]])

In [87]:
np.sort(random_array)

array([[3, 3, 3, 4, 7],
       [1, 4, 5, 9, 9],
       [0, 1, 7, 8, 9]])

In [88]:
random_array


array([[4, 7, 3, 3, 3],
       [1, 9, 9, 5, 4],
       [8, 7, 9, 0, 1]])

In [90]:
# show this index sorted
np.argsort(random_array)


array([[2, 3, 4, 0, 1],
       [0, 4, 3, 1, 2],
       [3, 4, 1, 0, 2]])

# Practical Example
![panda image](img/panda.png)

In [91]:
# turn image into numpy
from matplotlib.image import imread

panda = imread("img/panda.png")
print(type(panda))


<class 'numpy.ndarray'>


In [92]:
panda.size, panda.shape, panda.ndim


(24465000, (2330, 3500, 3), 3)

In [93]:
panda[:4]


array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.